=== Grimmar/Bdtheque/src/main/webapp/WEB-INF/bd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bd="http://univ-rouen.fr/bd"
            targetNamespace="http://univ-rouen.fr/bd">
    <xsd:import schemaLocation="http://www.xfront.com/isbn.xsd"/>
	
    <!-- definition of simple elements -->
    <xsd:element name="titre" type="xsd:string" />
    <xsd:element name="numero" type="xsd:float" />
    <xsd:element name="informations" type="xsd:string" />
    <xsd:element name="depotLegal" type="bd:partialDateType" />
    <xsd:element name="finImpression" type="bd:partialDateType" />
    <xsd:element name="parution" type="xsd:date" />
    <xsd:element name="editeur" type="xsd:string" />
    <xsd:element name="resume" type="xsd:string" />
    <xsd:element name="nom" type="xsd:string" />
    <xsd:element name="prenom" type="xsd:string" />
    <xsd:element name="format" type="xsd:string" />
    <xsd:element name="creation" type="xsd:date" />
    <xsd:element name="image" type="xsd:anyURI" />
    <xsd:element name="scenariste" type="bd:individuType" />
    <xsd:element name="dessinateur" type="bd:individuType" />
    <xsd:element name="coloriste" type="bd:individuType" />
    <xsd:element name="lettrage" type="bd:individuType" />
    <xsd:element name="encrage" type="bd:individuType" />
	
    <!-- definition of attributes -->
    <xsd:attribute name="planches" type="xsd:positiveInteger"/> 
    <xsd:attribute name="serie" type="xsd:string" default="One Shot"/> 
    <xsd:attribute name="langue" type="xsd:string"/>
    <xsd:attribute name="isbn" type="xsd:string"/>
	
    <!-- definition of complex elements -->
    <xsd:element name="bd" type="bd:bdType" />
    <xsd:element name="scenaristes" type="bd:scenaristesType" />
    <xsd:element name="dessinateurs" type="bd:dessinateursType" />
    <xsd:element name="coloristes" type="bd:coloristesType" />
    <xsd:element name="lettrages" type="bd:lettragesType" />
    <xsd:element name="encrages" type="bd:encragesType" />
    <xsd:element name="tome" type="bd:tomeType" />
	
		
    <!-- definition of simple types -->
    <xsd:simpleType name="partialDateType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern
                value="(((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[0-2])))|((((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012])))-((0[1-9])|([12][0-9])|(3[0-1])))" />
        </xsd:restriction>
    </xsd:simpleType>
	
    <xsd:simpleType name="langueType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="^[A-Z]{2}$"/>
        </xsd:restriction>
    </xsd:simpleType>
	
    <!-- definition of complex types -->
		
    <xsd:complexType name="individuType">
        <xsd:sequence>
            <xsd:element ref="bd:nom" minOccurs="1" maxOccurs="1" />
            <xsd:element ref="bd:prenom" minOccurs="0" maxOccurs="1" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="bdType">
        <xsd:sequence>
            <xsd:element name="titre" type="xsd:string" />
            <xsd:element name="depotLegal" type="bd:partialDateType" />
            <xsd:element name="finImpression" type="bd:partialDateType" />
            <xsd:element name="parution" type="xsd:date" />
            <xsd:element name="editeur" type="xsd:string" />
            <xsd:element name="resume" type="xsd:string" />
            <xsd:element name="format" type="xsd:string" />
            <xsd:element name="creation" type="xsd:date" />
            <xsd:element name="image" type="xsd:anyURI" />
            <xsd:element ref="bd:scenaristes" minOccurs="1" maxOccurs="1" />
            <xsd:element ref="bd:dessinateurs" minOccurs="1" maxOccurs="1" />
            <xsd:element ref="bd:coloristes" minOccurs="1" maxOccurs="1" />
            <xsd:element ref="bd:lettrages" minOccurs="0" maxOccurs="1" />
            <xsd:element ref="bd:encrages" minOccurs="0" maxOccurs="1" />
            <xsd:element ref="bd:tome" minOccurs="0" maxOccurs="1" />
        </xsd:sequence>
        <xsd:attribute ref="bd:isbn" use="required" />
        <xsd:attribute ref="bd:serie" use="required" />
        <xsd:attribute ref="bd:planches" use="required" />
        <xsd:attribute ref="bd:langue" use="required" />
    </xsd:complexType>
	
    <xsd:complexType name="scenaristesType">
        <xsd:sequence>
            <xsd:element ref="bd:scenariste" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="dessinateursType">
        <xsd:sequence>
            <xsd:element ref="bd:dessinateur" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="coloristesType">
        <xsd:sequence>
            <xsd:element ref="bd:coloriste" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="lettragesType">
        <xsd:sequence>
            <xsd:element ref="bd:lettrage" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="encragesType">
        <xsd:sequence>
            <xsd:element ref="bd:encrage" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
	
    <xsd:complexType name="tomeType">
        <xsd:sequence>
            <xsd:element ref="bd:numero" minOccurs="1" maxOccurs="1" />
            <xsd:element ref="bd:informations" minOccurs="1" maxOccurs="1" />
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== Grimmar/Bdtheque/src/main/java/fr/univ_rouen/bd/controller/bd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<ns1:bd
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://univ-rouen.fr/bd'
    xsi:schemaLocation='http://univ-rouen.fr/bd bd.xsd'
    ns1:isbn="9781401240936" ns1:planches="40" ns1:langue="FR" ns1:serie=""> 
    <titre>Hellblazer Death and cigarettes</titre>
    <numero>1.0</numero>
    <informations></informations>
    <depotLegal>2013-04</depotLegal>
    <finImpression>2013-04</finImpression>
    <parution>2013-03-19</parution>
    <editeur>Planeta DeAgostini</editeur>
    <resume>John Constantine had no intention of tracking down his long-lost nephew, despite the promise John made to his dead mom. But mysterious circumstances and a series of murders set Constantine out to Ireland in search of his forgotten relative. However, after a s√©ance with his late sister Cheryl, Constantine finds that there might be a lot more connections between his nephew and these set of murders than meets the eye.
        In this penultimate chapter to Vertigo's longest series, Death and Cigarettes is the latest chapter in critically acclaimed writer Peter Milligan's run on HELLBLAZER.
    </resume>
    <format>Format comics</format>
    <creation>2013-03-19</creation>
    <image>http://www.bedetheque.com/thb_couv/Couv_185426.jpg</image>
    <ns1:scenaristes>
        <ns1:scenariste>
            <ns1:nom>Milligan</ns1:nom>
            <ns1:prenom>Pete</ns1:prenom>
        </ns1:scenariste>
    </ns1:scenaristes>
    <ns1:dessinateurs>
        <ns1:dessinateur>
            <ns1:nom>Camuncoli</ns1:nom>
            <ns1:prenom>Giuseppe</ns1:prenom>
        </ns1:dessinateur>
        <ns1:dessinateur>
            <ns1:nom>test</ns1:nom>
            <ns1:prenom>test</ns1:prenom>
        </ns1:dessinateur>
        <ns1:dessinateur>
            <ns1:nom>Camuncoli</ns1:nom>
            <ns1:prenom>Giuseppe</ns1:prenom>
        </ns1:dessinateur>
        <ns1:dessinateur>
            <ns1:nom>test</ns1:nom>
            <ns1:prenom>test</ns1:prenom>
        </ns1:dessinateur>
        <ns1:dessinateur>
            <ns1:nom>Camuncoli</ns1:nom>
            <ns1:prenom>Giuseppe</ns1:prenom>
        </ns1:dessinateur>
        <ns1:dessinateur>
            <ns1:nom>test</ns1:nom>
            <ns1:prenom>test</ns1:prenom>
        </ns1:dessinateur>
    </ns1:dessinateurs>
    <ns1:coloristes>
        <ns1:coloriste>
            <ns1:nom>Buccellato</ns1:nom>
            <ns1:prenom>Brian</ns1:prenom>
        </ns1:coloriste>
        <ns1:coloriste>
            <ns1:nom>test</ns1:nom>
            <ns1:prenom>test</ns1:prenom>
        </ns1:coloriste>
    </ns1:coloristes>
    <ns1:lettrages>
        <ns1:lettrage>
            <ns1:nom>test3</ns1:nom>
            <ns1:prenom>test3</ns1:prenom>
        </ns1:lettrage>
    </ns1:lettrages>
    <ns1:encrages>
        <ns1:encrage>
            <ns1:nom>test4</ns1:nom>
            <ns1:prenom>test4</ns1:prenom>
        </ns1:encrage>
        <ns1:encrage>
            <ns1:nom>test5</ns1:nom>
            <ns1:prenom>test5</ns1:prenom>
        </ns1:encrage>
    </ns1:encrages>
    <ns1:tome>
        <ns1:numero>300</ns1:numero>
        <ns1:informations></ns1:informations>
    </ns1:tome>

</ns1:bd>

=== Grimmar/Bdtheque/src/main/webapp/WEB-INF/bd.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:bd
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://univ-rouen.fr/bd'
    xsi:schemaLocation='http://univ-rouen.fr/bd bd.xsd'
    ns1:isbn="9781401240936" ns1:planches="40" ns1:langue="FR" ns1:serie=""> 
    <ns1:titre>Hellblazer Death and cigarettes</ns1:titre>
    <ns1:depotLegal>2013-04</ns1:depotLegal>
    <ns1:id>bd</ns1:id>
    <ns1:finImpression>2013-04</ns1:finImpression>
    <ns1:parution>2013-03-19</ns1:parution>
    <ns1:editeur>Planeta DeAgostini</ns1:editeur>
    <ns1:resume>John Constantine had no intention of tracking down his long-lost nephew, despite the promise John made to his dead mom. But mysterious circumstances and a series of murders set Constantine out to Ireland in search of his forgotten relative. However, after a s√©ance with his late sister Cheryl, Constantine finds that there might be a lot more connections between his nephew and these set of murders than meets the eye.
        In this penultimate chapter to Vertigo's longest series, Death and Cigarettes is the latest chapter in critically acclaimed writer Peter Milligan's run on HELLBLAZER.
    </ns1:resume>
    <ns1:format>Format comics</ns1:format>
    <ns1:creationDate>2013-03-19</ns1:creationDate>
    <ns1:image>http://www.bedetheque.com/thb_couv/Couv_185426.jpg</ns1:image>
    <ns1:scenaristes>
        <ns1:scenariste>
            <ns1:nom>Milligan</ns1:nom>
            <ns1:prenom>Pete</ns1:prenom>
        </ns1:scenariste>
    </ns1:scenaristes>
    <ns1:dessinateurs>
        <ns1:dessinateur>
            <ns1:nom>Camuncoli</ns1:nom>
            <ns1:prenom>Giuseppe</ns1:prenom>
        </ns1:dessinateur>
        <ns1:dessinateur>
            <ns1:nom>test</ns1:nom>
            <ns1:prenom>test</ns1:prenom>
        </ns1:dessinateur>
        <ns1:dessinateur>
            <ns1:nom>Camuncoli</ns1:nom>
            <ns1:prenom>Giuseppe</ns1:prenom>
        </ns1:dessinateur>
        <ns1:dessinateur>
            <ns1:nom>test</ns1:nom>
            <ns1:prenom>test</ns1:prenom>
        </ns1:dessinateur>
        <ns1:dessinateur>
            <ns1:nom>Camuncoli</ns1:nom>
            <ns1:prenom>Giuseppe</ns1:prenom>
        </ns1:dessinateur>
        <ns1:dessinateur>
            <ns1:nom>test</ns1:nom>
            <ns1:prenom>test</ns1:prenom>
        </ns1:dessinateur>
    </ns1:dessinateurs>
    <ns1:coloristes>
        <ns1:coloriste>
            <ns1:nom>Buccellato</ns1:nom>
            <ns1:prenom>Brian</ns1:prenom>
        </ns1:coloriste>
        <ns1:coloriste>
            <ns1:nom>test</ns1:nom>
            <ns1:prenom>test</ns1:prenom>
        </ns1:coloriste>
    </ns1:coloristes>
    <ns1:lettrages>
        <ns1:lettrage>
            <ns1:nom>test3</ns1:nom>
            <ns1:prenom>test3</ns1:prenom>
        </ns1:lettrage>
    </ns1:lettrages>
    <ns1:encrages>
        <ns1:encrage>
            <ns1:nom>test4</ns1:nom>
            <ns1:prenom>test4</ns1:prenom>
        </ns1:encrage>
        <ns1:encrage>
            <ns1:nom>test5</ns1:nom>
            <ns1:prenom>test5</ns1:prenom>
        </ns1:encrage>
    </ns1:encrages>
    <ns1:tome>
        <ns1:numero>300</ns1:numero>
        <ns1:informations></ns1:informations>
    </ns1:tome>

</ns1:bd>

=== Grimmar/Bdtheque/src/main/webapp/WEB-INF/bd1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:bd
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://univ-rouen.fr/bd'
    xsi:schemaLocation='http://univ-rouen.fr/bd bd.xsd'
    ns1:isbn="2746031701" ns1:planches="160 " ns1:langue="FR" ns1:serie="">
    <ns1:titre>Batman-Sombre reflet</ns1:titre>
    <ns1:depotLegal>2012-04</ns1:depotLegal>
    <ns1:finImpression>2012-03</ns1:finImpression>
    <ns1:parution>2012-04-11</ns1:parution>
    <ns1:editeur>Urban Comics</ns1:editeur>
    <ns1:resume>Tandis que le retour de James Gordon Jr. ravive les tensions au sein de son entourage et rouvre des cicatrices, Batman rencontre la fille du responsable de la mort de ses parents ! Tiraillé entre son attirance pour la jeune femme et son désir de vengeance, le chevalier noir a bien du mal à mener son enquête à terme. Et lorsque le Joker se joint à la danse, la tension monte d’un cran et vengeances et trahisons s’enchaînent à un rythme étouffant !</ns1:resume>
    <ns1:format>Format comics</ns1:format>
    <ns1:creationDate>2012-04-08</ns1:creationDate>
    <ns1:image>http://www.bedetheque.com/thb_couv/Couv_160824.jpg</ns1:image>
    <ns1:scenaristes>
        <ns1:scenariste>
            <ns1:nom>Snyder</ns1:nom>
            <ns1:prenom>Scott</ns1:prenom>
        </ns1:scenariste>
    </ns1:scenaristes>
    <ns1:dessinateurs>
        <ns1:dessinateur>
            <ns1:nom>Jock</ns1:nom>
            <ns1:prenom></ns1:prenom>
        </ns1:dessinateur>
        <ns1:dessinateur>
            <ns1:nom>Francavilla</ns1:nom>
            <ns1:prenom>Francesco</ns1:prenom>
        </ns1:dessinateur>
    </ns1:dessinateurs>
    <ns1:coloristes>
        <ns1:coloriste>
            <ns1:nom>Baron</ns1:nom>
            <ns1:prenom>David</ns1:prenom>
        </ns1:coloriste>
    </ns1:coloristes>
    <ns1:tome>
        <ns1:numero>2</ns1:numero>
        <ns1:informations></ns1:informations>
    </ns1:tome>

</ns1:bd>
